import { Mail } from 'lucide-react';
import LegalPageLayout from '../components/LegalPageLayout';

export default function TermsOfUsePage() {
  return (
    <LegalPageLayout>
      {/* Hero */}
      <div className="mb-10">
        <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">
          Terms of Use
        </h1>
        <p className="mt-3 text-base sm:text-lg text-slate-500 dark:text-slate-400">
          Scrubs To Be LLC &mdash; Effective Date: February 26, 2026
        </p>
      </div>

      {/* Document body */}
      <article className="text-[15px] sm:text-base leading-relaxed text-slate-700 dark:text-slate-300 space-y-8">
        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">1. Acceptance of Terms</h2>
          <p>These Terms of Use ("Terms") govern your access to and use of the Scrubs To Be platform ("Service"), operated by Scrubs To Be LLC, a Delaware limited liability company ("Company," "we," "our," or "us"). By creating an account or using the Service, you agree to be bound by these Terms. If you do not agree, you may not use the Service.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">2. Eligibility</h2>
          <p>You must be at least 18 years old to use the Service. By using the Service, you represent and warrant that you meet this requirement. The Service is intended for users located in the United States.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">3. Description of Service</h2>
          <p className="mb-3">Scrubs To Be provides AI-powered educational tools designed to assist medical students in exam preparation, including:</p>
          <ul className="list-disc ml-6 space-y-1 mb-3">
            <li>AI-generated practice questions</li>
            <li>Flashcards</li>
            <li>AI-powered learning assistance</li>
          </ul>
          <p>The Service is for educational purposes only. We do not provide medical advice, clinical instruction, or professional licensing guidance.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">4. No Medical or Professional Advice</h2>
          <p>The Service does not provide medical advice. Content generated by AI may contain inaccuracies. Users are responsible for independently verifying information before relying on it. Use of the Service does not guarantee exam results, licensing outcomes, or academic performance.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">5. Account Registration</h2>
          <p className="mb-3">To access the Service, you must create an account. You agree to:</p>
          <ul className="list-disc ml-6 space-y-1 mb-3">
            <li>Provide accurate information</li>
            <li>Maintain confidentiality of login credentials</li>
            <li>Be responsible for all activity under your account</li>
          </ul>
          <p>We reserve the right to suspend or terminate accounts for violations of these Terms.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">6. Subscription & Billing</h2>
          <p className="mb-3">The Service operates on a subscription model:</p>
          <ul className="list-disc ml-6 space-y-1 mb-3">
            <li>Monthly Plan: $29.99 per month</li>
            <li>Annual Plan: $299.99 per year</li>
          </ul>
          <p>A 3-day free trial is offered. By starting a trial or subscription, you authorize automatic recurring billing through Stripe unless cancelled prior to renewal. You may cancel at any time via your account dashboard. Cancellation prevents future billing but does not retroactively refund prior charges. All billing terms are further governed by our Refund Policy.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">7. Intellectual Property</h2>
          <p className="mb-3">All content, software, branding, questions, flashcards, AI outputs, and platform materials are the exclusive property of Scrubs To Be LLC. You may not:</p>
          <ul className="list-disc ml-6 space-y-1 mb-3">
            <li>Copy</li>
            <li>Redistribute</li>
            <li>Resell</li>
            <li>Reverse engineer</li>
            <li>Scrape content</li>
            <li>Share login access</li>
          </ul>
          <p>Unauthorized use may result in termination and legal action.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">8. Acceptable Use</h2>
          <p className="mb-3">You agree not to:</p>
          <ul className="list-disc ml-6 space-y-1 mb-3">
            <li>Share accounts</li>
            <li>Attempt to hack or disrupt the platform</li>
            <li>Upload malicious code</li>
            <li>Engage in fraudulent chargebacks</li>
            <li>Use the Service for unlawful purposes</li>
          </ul>
          <p>We reserve the right to suspend or terminate accounts at our sole discretion.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">9. AI Disclaimer</h2>
          <p>The Service uses artificial intelligence to generate educational content. AI-generated responses may be inaccurate, incomplete, or outdated. We make no warranties regarding the accuracy, reliability, or suitability of AI-generated content. Users assume full responsibility for reliance on any output.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">10. Limitation of Liability</h2>
          <p className="mb-3">To the maximum extent permitted by law, Scrubs To Be LLC shall not be liable for:</p>
          <ul className="list-disc ml-6 space-y-1 mb-3">
            <li>Academic outcomes</li>
            <li>Exam performance</li>
            <li>Indirect or consequential damages</li>
            <li>Lost profits</li>
            <li>Data loss</li>
          </ul>
          <p>Our total liability shall not exceed the amount paid by you in the preceding 12 months.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">11. Indemnification</h2>
          <p>You agree to indemnify and hold harmless Scrubs To Be LLC from any claims arising out of your use of the Service, violation of these Terms, or misuse of AI-generated content.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">12. Chargebacks & Fraud</h2>
          <p className="mb-3">Initiating fraudulent chargebacks may result in:</p>
          <ul className="list-disc ml-6 space-y-1 mb-3">
            <li>Immediate account suspension</li>
            <li>Permanent ban</li>
            <li>Submission of evidence to payment processors</li>
          </ul>
          <p>We reserve all rights to recover funds and associated costs.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">13. Termination</h2>
          <p>We may suspend or terminate your account at any time for violations of these Terms. Upon termination, access to the Service will cease.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">14. Governing Law</h2>
          <p>These Terms are governed by the laws of the State of Delaware, United States. Any disputes shall be resolved in Delaware courts.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">15. Changes to Terms</h2>
          <p>We reserve the right to update these Terms at any time. Continued use of the Service constitutes acceptance of revised Terms.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">16. Contact Information</h2>
          <p>
            Scrubs To Be LLC<br />
            Delaware, United States<br />
            Email:{' '}
            <a href="mailto:medkotha@gmail.com" className="text-indigo-600 dark:text-indigo-400 hover:underline">medkotha@gmail.com</a>
          </p>
        </section>
      </article>

      {/* Contact CTA */}
      <div className="mt-14 rounded-2xl border border-slate-200 dark:border-slate-700 bg-gradient-to-br from-indigo-50 to-white dark:from-indigo-900/20 dark:to-slate-800/50 p-6 sm:p-8 text-center">
        <Mail className="w-8 h-8 text-indigo-600 dark:text-indigo-400 mx-auto mb-3" />
        <h3 className="text-lg font-bold text-slate-900 dark:text-white mb-2">Have questions about our terms?</h3>
        <p className="text-sm text-slate-500 dark:text-slate-400 mb-4">Reach out and we'll get back to you as soon as possible.</p>
        <a
          href="mailto:medkotha@gmail.com"
          className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-indigo-600 text-white text-sm font-semibold hover:bg-indigo-700 transition-colors shadow-lg shadow-indigo-200 dark:shadow-none"
        >
          <Mail className="w-4 h-4" />
          medkotha@gmail.com
        </a>
      </div>
    </LegalPageLayout>
  );
}
